default:
	echo compling code....
	javac -d bin -sourcepath src src/EVALUATOR/Evaluator.java

clean:
	rm -f bin/*/*

error1:
	cat error1.max

error1x:
	dpl error1.max

error2:
	cat error2.max

error2x:
	dpl error2.max

error3:
	cat error3.max

error3x:
	dpl error3.max

error4:
	cat error4.max

error4x:
	dpl error4.max

error5:
	cat error5.max

error5x:
	dpl error5.max

arrays:
	java -classpath bin PARSER.Parser array.max

arraysx:
	dpl array.max

conditionals:
	java -classpath bin PARSER.Parser conditionals.max

conditionalsx:
	dpl conditionals.max

recursion:
	java -classpath bin PARSER.Parser fibonacci.max

recursionx:
	dpl fibonacci.max

iteration:
	java -classpath bin PARSER.Parser iterator.max

iterationx:
	dpl iterator.max

functions:
	java -classpath bin PARSER.Parser functions.max

functionsx:
	dpl functions.max

lambda:
	java -classpath bin PARSER.Parser lambda.max

lambdax:
	dpl lambda.max

dictionary:
	java -classpath bin PARSER.Parser dictionary.max

dictionaryx:
	dpl dictionary.max

problem:
	java -classpath bin PARSER.Parser problem.max

problemx:
	dpl problem.max

grad:
	java -classpath bin PARSER.Parser grad.max

gradx:
	dpl grad.max
	java -classpath bin PARSER.Parser itssopretty.max
	dpl itssopretty.max

pretty:
	java -classpath bin PARSER.Parser itssopretty.max
	dpl itssopretty.max

avl:
	java -classpath bin PARSER.Parser avl.max
	dpl avl.max